version: '3'
services:
  web:
    image: microstore/microstore
    ports:
      - 8080:8080
    links:
      - mysql
      - minio
      - rabbitmq

  mysql:
    image: custom-mysql
    container_name: first_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command:
      server /export

  rabbitmq:
    image: rabbitmq
    hostname: rabbit1
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: rabbitmq

